policy:
  - name: "cloudtrail-name-to-create"
    s3_bucket_name: "s3-bucket-to-collect-cloudtrail-logs"
    enable_logging: ~
    enable_log_file_validation: ~
    sns_topic_name: ~
    is_multi_region_trail: ~
    include_global_service_events: ~
    cloud_watch_logs_role_arn: ~
    cloud_watch_logs_group_arn: ~
    kms_key_id: ~
    is_organization_trail: ~
    s3_key_prefix: ~
    insight_selector: {ApiCallRateInsight: true, ApiErrorRateInsight: true}
    tags: ~
