policy:
  - name: "cloudtrail-name-to-create"
    s3_bucket_name: "aws-cloudtrail-logs-362252864672-d1626848"
    enable_logging: ~
    enable_log_file_validation: ~
    sns_topic_name: ~
    is_multi_region_trail: ~
    include_global_service_events: ~
    cloud_watch_logs_role_arn: ~
    cloud_watch_logs_group_arn: ~
    kms_key_id: ~
    is_organization_trail: ~
    s3_key_prefix: ~
    insight_selector: {ApiCallRateInsight: true, ApiErrorRateInsight: true}
    event_selector: {
      read_write_type: "All",
      include_management_events: true,
      exclude_management_event_sources : ~
    }
    tags: ~
